apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: portfolio-service
  name: portfolio-service
spec:
  selector:
    matchLabels:
      app: portfolio-service
  replicas: 1
  template:
    metadata:
      labels:
        app: portfolio-service
    spec:
      containers:
        - name: portfolio-service
          image: portfolio-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: portfolio-service
  name: portfolio-service
spec:
  selector:
    app: portfolio-service
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8081
  type: LoadBalancer

